# 웹서버 배포 시스템 CodeDeploy 설정
# CodeDeploy 버전. 프로젝트 버전이 아닌 경우 0.0 이외 버전을 사용하면 오류 발생
version: 0.0
os: linux
files:
  - source: /   # CodeDeploy 에서 전달해준 파일 중 destination 으로 이동시킬 대상 지정. / 로 지정하면 전체파일 해당
    destination: /home/ec2-user/app/step3/zip/  # source 에서 지정된 파일을 받기 위한 위치. 이후 Jar 실행등은 destination 에서 옮긴 파일들로 진행
    overwrite: yes  # 기존 파일 덮어쓸지 여부. yes : 덮어 씀

# CodeDeploy 에서 EC2 서버로 넘겨준 파일들 모두 ec2-user 권한을 갖도록 조정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어 지정.
hooks:
  AfterInstall:
    - location: stop.sh # Nginx 와 연결되어있지 않은 스프링 부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart: # ApplicationStart 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 함
    - location: start.sh  # Nginx 와 연결되어있지 않은 Port(stop.sh 에서 종료한 profile 로 실행)로 새 버전의 스프링부트를 시작.
      timeout: 60   # 스크립트가 60초 이상 수행되면 실패 처리. 무한정 기다릴 수 없으니 시간제한을 둬 야 함
      runas: ec2-user
  ValidateService:
    - location: health.sh   # start.sh 로 실행시킨 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout:60
      runas: ec2-user

# switch.sh   Nginx 가 바라보는 스프링 부트를 최신 버전으로 변경
# profile.sh  앞선 4개 스크립트 파일에서 공용으로 사용할 'profile' 과 포트 체크 로직